version: "3.8"

services:
  backend:
    build: ./serverSide/backend
    container_name: backend
    expose:
      - "4000"

  client:
    build: ./clientSide/client
    container_name: client
    volumes:
      - client_build:/client

  admin:
    build: ./clientSide/admin
    container_name: admin
    volumes:
      - admin_build:/admin

  vendor:
    build: ./clientSide/vendor
    container_name: vendor
    volumes:
      - vendor_build:/vendor

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - client_build:/usr/share/nginx/html/client
      - admin_build:/usr/share/nginx/html/admin
      - vendor_build:/usr/share/nginx/html/vendor
    depends_on:
      - backend
      - client
      - admin
      - vendor

volumes:
  client_build:
  admin_build:
  vendor_build:
