# version: "29.1.3"

services:
  # mongodb:
  #   image: mongo:6
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - fullstack-net
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - admin
      - client
      - vendor
      - serverside

  serverside:
    build: ./serverside/backend
    container_name: express-server
    ports:
      - "4000:4000"
    env_file:
      - ./serverside/backend/.env
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./clientside/client
    container_name: react-client
    expose:
      - "3000"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped

  admin:
    build: ./clientside/admin
    container_name: react-admin
    expose:
      - "3001"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped

  vendor:
    build: ./clientside/vendor
    container_name: react-vendor
    expose:
      - "3002"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped




networks:
  fullstack-net:
    driver: bridge

# volumes:
#   mongo_data:
    # docker compose up
    # docker compose down
