# version: "3.9"

services:
  serverside:
    build: ./serverside/backend
    container_name: express-server
    ports:
      - "4000:4000"
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./clientside/client
    container_name: react-client
    ports:
      - "5173:3000"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped

  admin:
    build: ./clientside/admin
    container_name: react-admin
    ports:
      - "5174:3001"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped

  vendor:
    build: ./clientside/vendor
    container_name: react-vendor
    ports:
      - "5175:3002"
    networks:
      - fullstack-net
    depends_on:
      - serverside
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge


# docker compose up